---
title: "Armed Conflict Imputation"
format: html
editor: visual
---

## Models

Import Libraries

```{r}
#|output = false
#|echo = false
library(tidyverse)
library(xtable)
library(readr)
library(stargazer)
library(mice)
# library(plm)

```

Import Armed Conflict Data Set and Log Transform GDP

```{r}
#|echo = false
final_dat <- read_csv("../data/armed_conflict.csv")
final_dat <- final_dat[-1]
final_dat$gdp1000 <- log(final_dat$gdp1000 + 1)
final_dat <- final_dat %>% mutate(pctpopdens = popdens/100)
is.na(final_dat) <- sapply(final_dat, is.infinite)
# final_dat <- final_dat %>% mutate_all(~replace(., is.na(.), 0))
```

Imputation

```{r}
#|echo = false
#change ISO to numeric
midata <- final_dat |>
  mutate(ISOnum = as.numeric(as.factor(final_dat$ISO))) |>
  select(-country_name, -ISO)

# dry run
mice0  <- mice(midata, seed = 100, m = 5, maxit = 0, print = F)

meth <- mice0$method
meth[c("urban", "male_edu", "temp", "rainfall1000", "matmor", "infmor", "neomor", "under5mor", "gdp1000", "popdens")] <- "2l.lmer"

pred <- mice0$predictorMatrix
pred[c("urban", "male_edu", "temp", "rainfall1000", "matmor", "infmor", "neomor", "under5mor", "gdp1000", "popdens"), "ISOnum"] <- -2

# multiple imputation
mice.multi.out  <- mice(midata, seed = 100, m = 10, maxit = 20,
                        method = meth,
                        predictorMatrix = pred)

plot(mice.multi.out)
```

Models

```{r}
preds <- as.formula(" ~ armconf1 + gdp1000 + OECD + popdens + urban + 
                  agedep + male_edu + temp + rainfall1000 + earthquake + drought + 
                  ISO + as.factor(year)")

matmormod <- with(mice.multi.out, 
                      lm(matmor ~ -1 + armconf1 + gdp1000 + OECD +
                           popdens + urban + 
                           agedep + male_edu + temp + rainfall1000 +
                           earthquake + drought + 
                           as.factor(ISOnum) + as.factor(year)))
un5mormod <- with(mice.multi.out, 
                      lm(under5mor ~ -1 + armconf1 + gdp1000 + OECD +
                           popdens + urban + 
                           agedep + male_edu + temp + rainfall1000 +
                           earthquake + drought + 
                           as.factor(ISOnum) + as.factor(year)))
infmormod <- with(mice.multi.out, 
                      lm(infmor ~ -1 + armconf1 + gdp1000 + OECD +
                           popdens + urban + 
                           agedep + male_edu + temp + rainfall1000 +
                           earthquake + drought + 
                           as.factor(ISOnum) + as.factor(year)))
neomormod <- with(mice.multi.out, 
                      lm(neomor ~ -1 + armconf1 + gdp1000 + OECD +
                           popdens + urban + 
                           agedep + male_edu + temp + rainfall1000 +
                           earthquake + drought + 
                           as.factor(ISOnum) + as.factor(year)))
```

Pooling

```{r}
out.matmor <- pool(matmormod)
out.infmor <- pool(infmormod)
out.neomor<- pool(neomormod)
out.un5mor <- pool(un5mormod)
```

```{r}
compare <- list(out.matmor, out.infmor, out.neomor, out.un5mor, 
               matmormod, un5mormod, infmormod, neomormod)
```

Combine the other covariates

```{r}
keepvars <- list("armconf1" = "Armed conflict",
                 "loggdp" = "log(GDP)",
                 "OECD" = "OECD",
                 "pctpopdens" = "Population density",
                 "urban" = "Urban",
                 "agedep" = "Age dependency",
                 "male_edu" = "Male education",
                 "temp" = "Average temperature",
                 "rainfall" = "Average rainfall",
                 "earthquake" = "Earthquake",
                 "drought" = "Drought")

```

```{r}
#|output = false
#|echo = false
# Use stargazer to display the table
screenreg(tosave, 
       ci.force = TRUE,
       custom.coef.map = keepvars,
       custom.model.names = c("Mat CC", "Mat MI", "Un5 CC", "Un5 MI", "Inf CC", "Inf MI", "Neo CC", "Neo MI"))

save(tosave, file = here("output", "mi_output.Rdata"))
```
