---
title: "armedconflict_models"
format: html
editor: visual
---

## Models

Import Libraries

```{r}
#|output = false
#|echo = false
library(tidyverse)
library(xtable)
library(readr)
library(stargazer)
library(plm)

```

Import Armed Conflict Data Set and Log Transform GDP

```{r}
#| echo: false
final_dat <- read_csv("data/armed_conflict.csv")
final_dat$gdp1000 <- log(final_dat$gdp1000 + 1)
is.na(final_dat) <- sapply(final_dat, is.infinite)
final_dat <- final_dat %>% mutate_all(~replace(., is.na(.), 0))
```

Models

```{r}
preds <- as.formula(" ~ armconf1 + gdp1000 + OECD + popdens + urban + 
                  agedep + male_edu + temp + rainfall1000 + earthquake + drought + 
                  ISO + as.factor(year)")


matmormod <- plm(update.formula(preds, matmor ~ .), index = c("ISO", "year"),
                 effect = "twoways",
                 model = "within",
                 data = final_dat)
un5mormod <- plm(update.formula(preds, under5mor ~ .), index = c("ISO", "year"),
                effect = "twoways",
                model = "within", data = final_dat)
infmormod <- plm(update.formula(preds, infmor ~ .), index = c("ISO", "year"),
                effect = "twoways",
                model = "within", data = final_dat)
neomormod <- plm(update.formula(preds, neomor ~ .), index = c("ISO", "year"),
                effect = "twoways",
                model = "within", data = final_dat)
```

'Slice' out armed conflict data
```{r}
models <- list(matmormod, un5mormod, infmormod, neomormod)

# Extracting armconf1 coefficients
armed_conflict_coefs <- sapply(models, function(model){ coef(model)["armconf1"]})

# Create a data frame with "Yes" and "No" rows
armed_conflict_coefs <- t(data.frame(
  "No Armed Conflict" = rep(0, length(armed_conflict_coefs)),          # 0 for "No" rows
  "Yes Armed Conflict" = armed_conflict_coefs))                         # Coefficient for "Yes" rows

colnames(armed_conflict_coefs) <- c("Maternal Mortality",
                                "Under 5 Mortality",
                                "Infant Mortality",
                                "Neonatal Mortality") # Name columns by model
```

Combine the other covariates

```{r}
other_coefs <- as.data.frame(sapply(models, function(model){ coef(model)[-1]}))

colnames(other_coefs) <- c("Maternal Mortality",
                                     "Under 5 Mortality",
                                     "Infant Mortality",
                                     "Neonatal Mortality")

armed_conf_table <- rbind(armed_conflict_coefs, other_coefs)

```


```{r}
#|output = false
#|echo = false
# Use stargazer to display the table
s <- stargazer(armed_conf_table, type = "html", title = "Armed Conflict Binary for Mortality Models", out = c("Figures/mordmodel.html"), summary = FALSE, rownames = TRUE)
```
